"""empty message

Revision ID: 2d9668333511
Revises: None
Create Date: 2015-04-28 02:08:47.042653

"""

# revision identifiers, used by Alembic.
revision = '2d9668333511'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    ### end Alembic commands ###
